export {
  MEMORY_UNIT_TYPES,
  MEMORY_UNIT_STATUSES,
  SOURCE_ASSET_KINDS,
  ARCHIVE_ANCHOR_SCOPES,
  RETRIEVAL_REF_KINDS,
  RETRIEVAL_SOURCES,
  DATA_LAYER_SEARCH_TARGETS,
  isMemoryUnitType,
  isMemoryUnitStatus,
  isSourceAssetKind,
  isArchiveAnchorScope,
  isRetrievalRefKind,
  isRetrievalSource,
  isDataLayerSearchTarget,
  isSourceAnchor,
  isRetrievalScope,
  isRetrievalQuery,
  isRetrievalReference,
  isSessionRecord,
  isSessionDetail,
  isMemoryUnit,
  isSourceAsset,
  isArchiveAnchor,
  isDataLayerSearchQuery,
  isDataLayerSearchHit,
  isDataLayerSearchResponse,
  isEntityGraphNodeView,
  isEntityGraphEdgeView,
  isEntityGraphView,
  isCommitContext,
  normalizeRetrievalQuery,
  normalizeDataLayerSearchQuery,
  toEffectiveRetrievalLimit,
  compareRetrievalReferences,
  dedupeRetrievalReferences,
} from './domain.js'

export type { DataLayerAPI, DataLayerDependencies } from './data-layer-api.js'
export { createDataLayerAPI } from './data-layer-api.js'
